"""One-time script to read XES3G5M kc_routes_map.json and produce concept_tags.py.

Usage:
    python -m backend.scripts.build_concept_map --kc-routes-map /path/to/kc_routes_map.json

The script reads the Chinese KC names, translates them to English via Google
Translate, and writes the result to backend/app/concept_tags.py.
"""

from __future__ import annotations

import argparse
import json
import sys
import textwrap
import time
from pathlib import Path


def _translate_batch(texts: list[str], batch_size: int = 50) -> list[str]:
    try:
        from deep_translator import GoogleTranslator
    except ImportError:
        print("deep-translator not installed. Install with: pip install deep-translator", file=sys.stderr)
        sys.exit(1)

    translator = GoogleTranslator(source="zh-CN", target="en")
    results: list[str] = []
    for i in range(0, len(texts), batch_size):
        batch = texts[i : i + batch_size]
        joined = "\n".join(batch)
        try:
            translated = translator.translate(joined)
            parts = translated.split("\n")
            if len(parts) == len(batch):
                results.extend(parts)
            else:
                for text in batch:
                    results.append(translator.translate(text))
                    time.sleep(0.1)
        except Exception:
            for text in batch:
                try:
                    results.append(translator.translate(text))
                except Exception:
                    results.append(text)
                time.sleep(0.1)
        time.sleep(0.3)
        print(f"  Translated {min(i + batch_size, len(texts))}/{len(texts)}", flush=True)
    return results


def _title_case(s: str) -> str:
    return " ".join(word.capitalize() if word.lower() not in {"a", "an", "the", "of", "in", "and", "or", "for", "to", "with", "by", "at", "on"} else word for word in s.split())


def main() -> None:
    parser = argparse.ArgumentParser(description="Build concept_tags.py from kc_routes_map.json")
    parser.add_argument("--kc-routes-map", type=Path, required=True, help="Path to kc_routes_map.json")
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "app" / "concept_tags.py",
        help="Output path for concept_tags.py",
    )
    args = parser.parse_args()

    with args.kc_routes_map.open("r", encoding="utf-8") as f:
        raw: dict[str, str] = json.load(f)

    concept_ids = sorted(int(k) for k in raw.keys())
    chinese_names = [raw[str(cid)] for cid in concept_ids]

    print(f"Loaded {len(concept_ids)} concept entries. Translating...")
    english_names = _translate_batch(chinese_names)

    lines = [
        '"""Auto-generated mapping of XES3G5M concept IDs to English labels.',
        "",
        "Generated by backend/scripts/build_concept_map.py from kc_routes_map.json.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "",
        "CONCEPT_TAG_MAP: dict[int, str] = {",
    ]
    for cid, en_name in zip(concept_ids, english_names):
        cleaned = en_name.strip().replace('"', '\\"')
        cleaned = _title_case(cleaned)
        lines.append(f'    {cid}: "{cleaned}",')
    lines.append("}")
    lines.append("")
    lines.append("")
    lines.append("def get_tag_label(concept_id: int | str) -> str:")
    lines.append('    """Return the English label for a concept ID, with fallback."""')
    lines.append("    try:")
    lines.append("        cid = int(concept_id)")
    lines.append("    except (TypeError, ValueError):")
    lines.append('        return f"Concept {concept_id}"')
    lines.append('    return CONCEPT_TAG_MAP.get(cid, f"Concept {cid}")')
    lines.append("")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(concept_ids)} entries to {args.output}")


if __name__ == "__main__":
    main()
